openapi:
  title: teste API
  version: 1.0.0
  description: API gerada automaticamente pelo Vaden.
  enable: true

#É interessante remover isso daqui, pois o usuário pode facilmente comentar
#e ter problemas sem saber identificar
server:
  port: 8080
  host: localhost

#Dependencia do banco de dados
postgres:
  host: 0.0.0.0
  password: '123456'
  database: banco_teste
  port: 5432
  username: admin
  ssl: disable

storage:
  provider: local  # opções: local, s3, firebase
  local:
    folder: './uploads'
  s3:
    bucket: 'meu-bucket'
    region: 'us-east-1'
    accessKey: 'sua_access_key'
    secretKey: 'seu_secret_key'
  firebase:
    projectId: 'my-project'
    apiKey: 'my_api'

env:
  base_url: http://localhost
  mode: debug