name: teste
description: Projeto feito para primeiro teste no vaden.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  postgres: ^3.5.4
  dio: ^5.8.0+1
  vaden: ^0.0.7
  result_dart: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^0.0.7